### ISSUE TITLE
Expose the `stroke-linecap` property

### ISSUE THREAD

**Issue by avdaredevil** [tehapo/progress-bubble#2]
Hey great library. But my app requires a more flat and metro design.

Could you please offer a property/expose the `stroke-linecap` svg property so that it can be set to

```
    stroke-linecap: butt;
```

**Comment by tehapo** [comment]
Thanks for the feedback!

The new feature is available in v1.2.0 which I just released.

**Comment by avdaredevil** [comment]
Awesome! Thanks
