### ISSUE TITLE
Move styling inside template tag

### ISSUE THREAD

**Issue by trading-peter** [tehapo/progress-bubble#7]
I experienced leaking styling with progress-bubble because of https://github.com/tehapo/progress-bubble/blob/master/progress-bubble.html#L18.

the `svg, div` selector was applied to other elements in my web app and made them invisible because of `opacity: 0`, so I changed it to `:host svg, :host div`. That stopped the leakage.

Now it struck me that the problem may be that the `<style>` tag is **outside** of `<template>`.
Regardless whether this is the cause or not, it would be advisable anyway to move the styling inside the template, I guess.

**Comment by tehapo** [comment]
You're right, the `<style>` tag should be inside the `<template>`. 👍
